# Generated by Django 5.1 on 2024-09-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='A.jpg', upload_to='profile_pictures'),
        ),
    ]
